// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class ShortUrl
{
    public int Id { get; set; }

    public string LongUrl { get; set; }

    public string ShortUrl1 { get; set; }

    public string ShortCode { get; set; }

    public DateTime CreatedAt { get; set; }
}